import axios from 'axios';
import Head from 'next/head'
import NoResults from '../components/NoResults';
import VideoCard from '../components/VideoCard';
import { Video } from '../types'
import { BASE_URL } from '../utils';

type VideoProps = {
  videos: Video[]
}

export default function Home({ videos }: VideoProps) {
  

  return (
    <div className=''>
      <Head>
        <title>TikTik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="tiktik-logo.ico" />
      </Head>

      <section className='flex flex-col gap-10 videos h-full'>
        {videos.length ?
          videos.map((video: Video) => (
            <VideoCard post={video} key={video._id} />
          )) : (
            <NoResults text={'No Videos'} />
          )
        }
      </section>
    </div>
  )
}


export const getServerSideProps = async ({
  query: { topic },
}: {
  query: { topic: string };
}) => {
  let response = await axios.get(`${BASE_URL}/api/post`);

  if(topic) {
    response = await axios.get(`${BASE_URL}/api/discover/${topic}`);
  }
  
  return {
    props: { videos: response.data },
  };
};