import Head from 'next/head'
import NoResults from '../components/NoResults';
import VideoCard from '../components/VideoCard';
import { Video } from '../types'

type VideoProps = {
  videos: Video[]
}

export default function Home({ videos }: VideoProps) {
  
  return (
    <div className=''>
      <Head>
        <title>TikTik</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="tiktik-logo.ico" />
      </Head>

      <section className='flex flex-col gap-10 videos h-full'>
        {videos.length?
        videos.map((video:Video)=>(
          <VideoCard post={video} key={video._id}/>
        )) :(
          <NoResults text={'No Videos'}/>
        ) 
      }
      </section>
    </div>
  )
}

export const getServerSideProps = async () => {

  const response = await fetch(`http://localhost:3000/api/post`)
  const data = await response.json()


  return {
    props: {
      videos: data
    }
  }
}